# serverless.yml

service: lambda-cors

provider:
  name: aws
  runtime: nodejs12.x
  stages:
    - dev
    - prd

functions:
  cors:
    handler: src/index.handler
    memorySize: 128
    events:
      - http:
          path: /
          method: get
          cors: true
